### ISSUE TITLE
没有校验国密加密证书，严重bug

### ISSUE THREAD

**Issue by gquanma** [BabaSSL/BabaSSL#113]
查看咱们代码，当前咱们应该是**没有对国密加密证书进行校验**，这似乎是个很严重的bug：加密证书有效时间，以及来源都没校验。请问咱们会进行这块的支持吗？或者是有规范写明无需校验国密加密证书(只需校验国密签名证书)？

**Comment by dongbeiouba** [comment]
我在本地环境使用s_client和s_server测试并没有发现你说的问题。

自签发有效期比较短的国密证书，包括加密证书和签名证书。
s_server启动时国密证书没有过期，开启国密NTLS，监听；
s_client连接服务端成功；
过一段时间，服务端证书过期，使用s_client连接服务端失败，并输出如下错误：
> Verification error: certificate has expired

建议再仔细看一下代码，或者提供一下bug的测试步骤和错误输出。

**Comment by gquanma** [comment]
> 我在本地环境使用s_client和s_server测试并没有发现你说的问题。
> 
> 自签发有效期比较短的国密证书，包括加密证书和签名证书。 s_server启动时国密证书没有过期，开启国密NTLS，监听； s_client连接服务端成功； 过一段时间，服务端证书过期，使用s_client连接服务端失败，并输出如下错误：
> 
> > Verification error: certificate has expired
> 
> 建议再仔细看一下代码，或者提供一下bug的测试步骤和日志输出。

测试场景：
签名证书正常，加密证书过期：
步骤：
1. s_server加载上边场景证书并启动，开启国密NTLS，监听；
2. s_client连接服务端成功；
预期：
显示加密证书过期
实际：
没有显示过期，能正常建链

签名证书：
notBefore=Dec  2 07:24:22 2020 GMT
notAfter=Jan 10 07:24:22 2025 GMT

加密证书：
notBefore=Apr  8 00:00:00 2020 GMT
notAfter=Apr  4 00:00:00 2020 GMT

**Comment by dongbeiouba** [comment]
经过测试，确实存在问题。

多谢！我们会尽快修复这个bug。

**Comment by gquanma** [comment]
1.看了修改的代码，好像只在服务端进行了加密证书的校验，在证书双向校验的场景下，或者ECDHE-xx算法套下，客户端也是要对证书进行校验的，这块是否要考虑一下？

2.在上面的问题基础上，又引出了一个问题：看代码，校验加密证书时，使用的是与签名证书相同的CA，如果签名证书与加密证书签发自不同CA呢？服务端/客户端发送证书消息时，是不是要带上不同的CA？

**Comment by InfoHunter** [comment]
1. 客户端的正在改，后续会改成校验证书是否来源于可信CA
2. 这个属于目前国密标准的模糊地带，尚没有明确的技术规范对TLCP/GMT0024握手过程中双证书以什么格式/结构传输进行规定。我们是根据和市场上一些主流的浏览器/密码厂商对接后，发现实际的应用场景大多是签名证书和加密证书签发自同一CA（引出的另外一个现象就是证书链只需要构造一次，因为签名和加密证书的中间CA以及根CA是完全相同的），所以BabaSSL暂时不考虑支持签名证书和加密证书来自于不同CA的情况（主要是构造含有中间CA的证书链的方式没有兼容性）。

这个问题的本质是整个双证书体系在类似TLS握手的流程中的使用，没有精确定义导致的。
