### ISSUE TITLE
SSL_set_cipher_list

### ISSUE THREAD

**Issue by 532810439** [BabaSSL/BabaSSL#120]
./Configure --prefix=/tmp/openssl --cross-compile-prefix= linux-armv4 no-asm no-shared -fPIC

配置后，NTLS是默认开启的吗？NTLS_server_method怎么没有定义。

**Comment by 532810439** [comment]
> SSL_set_cipher_list(ssl,SM4_CIPHERSUITES)接口报错，无法设置国密套件

**Comment by dongbeiouba** [comment]
> ./Configure --prefix=/tmp/openssl --cross-compile-prefix= linux-armv4 no-asm no-shared -fPIC
> 
> 配置后，NTLS是默认开启的吗？NTLS_server_method怎么没有定义。

NTLS默认是关闭的，需要加上enable-ntls

**Comment by dongbeiouba** [comment]
> ./Configure --prefix=/tmp/openssl --cross-compile-prefix= linux-armv4 no-asm no-shared -fPIC
> 
> 配置后，NTLS是默认开启的吗？NTLS_server_method怎么没有定义。

NTLS默认是关闭的，需要加上enable-ntls

**Comment by 532810439** [comment]
> > ./Configure --prefix=/tmp/openssl --cross-compile-prefix= linux-armv4 no-asm no-shared -fPIC
> > 配置后，NTLS是默认开启的吗？NTLS_server_method怎么没有定义。
> 
> NTLS默认是关闭的，需要加上enable-ntls

好的，感谢。

**Comment by 532810439** [comment]
> > ./Configure --prefix=/tmp/openssl --cross-compile-prefix= linux-armv4 no-asm no-shared -fPIC
> > 配置后，NTLS是默认开启的吗？NTLS_server_method怎么没有定义。
> 
> NTLS默认是关闭的，需要加上enable-ntls

请问，nginx使用套件的话，直接加上openssl路径，就可以支持国密ssl吗？

**Comment by dongbeiouba** [comment]
目前Nginx还不支持国密，需要修改代码适配。

可以参考一下https://babassl.readthedocs.io/zh/latest/Tutorial/SM/ntls/

后续我们会尝试向Nginx、Tengine等开源项目提交patch，支持国密通信。

**Comment by 532810439** [comment]
> 目前Nginx还不支持国密，需要修改代码适配。
> 
> 可以参考一下https://babassl.readthedocs.io/zh/latest/Tutorial/SM/ntls/
> 
> 后续我们会尝试向Nginx、Tengine等开源项目提交patch，支持国密通信。
大概理解了。不支持的原因是在原来openssl开源基础上增加了国密ssl的接口。

**Comment by InfoHunter** [comment]
> 大概理解了。不支持的原因是在原来openssl开源基础上增加了国密ssl的接口。

对，我们很快会在tengine上先把这部分接口支持起来
