### ISSUE TITLE
NTLS中使用ECDH做秘钥交换时，pms计算和国密标准流程不一致

### ISSUE THREAD

**Issue by stardrift1** [BabaSSL/BabaSSL#121]
https://github.com/BabaSSL/BabaSSL/blob/337bebbe457bcc9585a75576641097ef3341b35e/crypto/sm2/sm2_kep.c#L207

标准中的用户A应该就NTLS的服务端，那么计算KDF的时候，ZA也就是服务端Z值应该要放在前面，但是我们是放在后面的，是否存在bug呢？

**Comment by stardrift1** [comment]
6 密钥交换协议及流程
6.1 密钥交换协议
设用户 A和 B协商获得密钥数据的长度为 乃J‘ ″比特 ,用 户 A为 发起方 ,用 户 B为 响应方 。
用户 A和 B双方为了获得相同的密钥 ,应 实现如下运算步骤 :
记 钯=「 (「 log2(″ )l/2)l-1。
用户 A:
A1:用 随机数发生器产生随机数 杠 ∈[1,饣 -1];
A2:计算椭圆曲线点 RA=ErA彐 G=(=l,丿 l);
A3:将 RA发送给用户 B;
用户 B:
B1:用 随机数发生器产生随机数 Pˉ :∈ E1,″ -1];
B2:计 算椭圆曲线点 R:=Er:彐 G=(r2,丿2);
B3:从 R:中 取出域元素 J2,按 GM/T0003,1— ⒛124,2.8给 出的方法将 J2的 数据类型转换为整
数 ,计 算 Ξ2=2臼 +(J2&(2v-1焉 ;
B4:计 算 r:=(d:+Ξ2· PI3) mod″ ;
B5:验 证 RΛ 是 否 满 足 椭 圆 曲线 方 程 ,若 不 满 足 则 协 商 失 败 ;否 则 从 RA中 取 出域 元 素 rl,按
GM/T0003,1— ~90124.2.8给 出的方法将 J1的 数据类型转换为整数 ,计算 Ξ1=2贽 +(Jl&(2v-1));
B6:计 算椭 圆曲线点 y=E凡 .r:](PA+匚Ξ1]RΛ )=(Jv,为 ),若 V是无穷远点 ,则 B协商失败 ;否 则
按 GM/T0003,1— ⒛124.2,6和 4.2.5给 出的方法将 rv、 为 的数据类型转换为比特串;
B7:计 算 K:=KDF(Jv‖ 为 ‖zA||Z:,乃 Z纟 饣);
B8:(选 项)按 GM/T0003.1-20124.2.6和 4.2.5给 出的方法将 RA的 坐标 J1、 yl和 R:的 坐标
r2、 y2的 数据类型转换为比特串,计 算 S:=H曰 s九 (0x02‖ 为 ‖Ff夕 s九 (Jv‖ zA||民 ‖J1‖ yl‖ J2‖
丿2));
B9:将 R:、 (选 项 S:)发送给用户 A;
用户 A:
A4:从 RA中 取出域元素 r” 按 GM/T0003.1— 20124.2,8给 出的方法将 Jl的数据类型转换为整
数 ,计 算 Ξl=2肥 +(r1&(2v— 1));
A5:计算 莎A=(dA+Ⅰl· 气) mod″ ;
A6:验 证 R:是 否 满 足 椭 圆 曲线 方 程 ,若 不 满 足 则 协 商 失 败 ;否 则 从 R:中 取 出域 元 素 r2,按
GM/TO003.1— ⒛124.2,8给 出的方法将 ∝2的 数据类型转换为整数 ,计算 i2=2钯 +(J2&(2v-1));
A7:计算椭圆曲线点 U=E乃 ·rΛ 彐(P:+EⅠ2]R:)=(Ju,yu),若 Lr是 无穷远点 ,则 A协商失败;否
则按 GM/T0003.1— 20124,2.6和 4,2.5· 给出的方法将 =u、 丿u的 数据类型转换为比特串;
A8:计 算 **KA=KDF(rσ |丿v‖ zA||Z⒔ ,花 zPP,);**
A9:(选 项)按 GM/T0003.1— ⒛124.2.6和 4,2.5给 出的方法将 RΛ 的坐标 r¨ ~Jl和 R:的 坐标
r2、 丿2的 数据类型转换为 比特串,计 算 S1=H勿s九 (0xO2|γu‖ H曰 s九 (宓u‖ zA||z:||Jl‖ yl‖ r2‖
γ2)),并 检验 S1=S:是 否成立 ,若 等式不成立则从 B到 A的 密钥确认失败 ;
A10:(选 项 )计算 SA=Fr夕 s九 (oxfl3|丿u‖ H夕 s凡 (ru‖ zA||z:||Jl‖ γl‖ r2‖ γ2)),并 将 S、 发 送 给
用户 B。
用户 B:
B10:(选 项 )计 算 S2=Ff曰 s九 (0xO引 |为 ‖Ff曰 s九 (rv|zΛ |{z:|r1‖ y1‖ r2‖ 丿2)),并 检 验 S2=SA
是 否成 立 ,若 等式 不成 立则从 A到 B的 密钥确认 失败 。
注:如 果 zA、 z:不 是用户 A和 B所对应的杂凑值,则 自然不能达成一致的共享秘密值。密钥交换协议过程的示

**Comment by InfoHunter** [comment]
这是个问题，见：#122

**Comment by InfoHunter** [comment]
在下个大版本8.3.0里修复

**Comment by stardrift1** [comment]
好的
