### ISSUE TITLE
8.2.1 版本

### ISSUE THREAD

**Issue by 532810439** [BabaSSL/BabaSSL#125]
请问8.2.1 版本，国密ssl不支持ECC-SM2-WITH-SM4-SM3吗？客户端SSL_CTX_set_cipher_list以后，无法建立双向ssl通道

**Comment by InfoHunter** [comment]
config的时候`enable-ntls`了么？

**Comment by 532810439** [comment]
> config的时候`enable-ntls`了么？

加了。   如果用ECDHE-SM2-WITH-SM4-SM3，没问题的。刚刚比较了最新的代码和8.2.1中代码，ntls_process_cert_verify_ntls函数的实现是不一样的。

最新代码是：if ((alg_k & SSL_kSM2) || (alg_k & SSL_kSM2DHE))
而8.2.1 版本里是if (alg_k & SSL_kSM2DHE)

所以报错了。

**Comment by dongbeiouba** [comment]
对，8.2.1版本还不支持ECC-SM2客户端认证，这个问题在master分支已经解决了。

后续新版本会支持。

**Comment by 532810439** [comment]
> 对，8.2.1版本还不支持ECC-SM2客户端认证，这个问题在master分支已经解决了。
> 
> 后续新版本会支持。

好的。最新的稳定版本，有计划release吗？
