### ISSUE TITLE
TLCP协议的ECDHE_SM2_SM4_SM3套件是否一定需要校验客户端证书？

### ISSUE THREAD

**Issue by tangxiao187** [BabaSSL/BabaSSL#126]
按照GB/T 38636-2020的要求，ECDHE_SM2_SM4_SM3套件在握手过程是需要客户端发送证书的，但没有明确要求校验客户端证书的合法性。
按照之前BaBaSSL的实现，当协商的套件是ECDHE_SM2_SM4_SM3时，服务端自动发送CertificateRequest，并在tls_process_client_certificate_ntls处理客户端证书时忽略了证书校验结果，只把校验结果记录在verify_result供上层应用判断。
![image](https://user-images.githubusercontent.com/18070881/143834347-3a485458-84b9-4798-aa8d-20a8567fda5f.png)
在
commit cbc239f7加了客户端加密证书的校验功能后，如果上层应用程序没有启用双向认证和配置CA证书，tls_process_client_certificate_ntls会直接返回错误导致握手终止。
![image](https://user-images.githubusercontent.com/18070881/143834457-abef8f29-8f0e-4d8c-a089-a1beb5ad7ebd.png)

想咨询下，标准是否定义了ECDHE_SM2_SM4_SM3一定要校验客户端证书，还是可以只发送客户端证书参与密钥交换但不做校验？

**Comment by InfoHunter** [comment]
标准没定义一定要校验客户端证书，因为校验客户端证书这个定义本身就存比较模糊。对证书（无论是客户端还是服务器端）的校验可以分成很多不同层次，比如：

1. 对端发过来的证书链是否合法，即是不是一条合法的链；
2. 对端发过来的证书本身是否合法，比如证书是不是过期了、某些字段里的值是不是合法；
3. 对端证书所表示的身份信息是否是符合期望的，比如CN/SAN里的值是不是希望的目标域名之类的

从软件的层次来看，上述3个方面中，第三点肯定是得由应用程序自己判断，因为这些信息只有应用程序才知道。至于1和2既可以甩给应用程序来判断，也可以底层TLS库来判断/校验，就是尺度松和紧的问题，然而关于这个问题没有相关的标准来进行定义。BabaSSL的做法是稍微紧一些，所以就把证书链是否合法的校验在底层给做完了

**Comment by tangxiao187** [comment]
好的，多谢解答哈。
