### ISSUE TITLE
SM2 签名过程  

### ISSUE THREAD

**Issue by 532810439** [BabaSSL/BabaSSL#128]
ntls_construct_cert_verify_ntls和ntls_process_cert_verify_ntls中，sm2签名和验签的过程，利用跟踪出来的数据，发现对原文直接做sm3哈希，把结果直接当做签名或验签的哈希值了。

应该是先把计算Z值，再update原文数据，出来的结果，才可以当做签名或验签的哈希值(E值)

**Comment by dongbeiouba** [comment]
ntls_construct_cert_verify_ntls -> EVP_DigestSignInit -> do_sigver_init -> ctx->pctx->pmeth->digest_custom()

ctx->pctx->pmeth->digest_custom() 这里为pkey_sm2_digest_custom()。

pkey_sm2_digest_custom()中会计算Z值的，对应预处理1过程。

**Comment by 532810439** [comment]
> ntls_construct_cert_verify_ntls -> EVP_DigestSignInit -> do_sigver_init -> ctx->pctx->pmeth->digest_custom()
> 
> ctx->pctx->pmeth->digest_custom() 这里为pkey_sm2_digest_custom()。
> 
> pkey_sm2_digest_custom()中会计算Z值的，对应预处理1过程。

研究了下openssl源码，同意你说的，内部已经计算了Z值。

但是有一点，与我的理解不一致：

对原文的处理：
根据《GMT 0003.2-2012 SM2椭圆曲线公钥密码算法第2部分：数字签名算法》6.1中规定：Z值和原文是拼接的关系，而不是将Z值和原文哈希后拼接。

参考《SSL VPN规范》6.4.4.8中描述，运算内容的部分。

**Comment by dongbeiouba** [comment]
> > ntls_construct_cert_verify_ntls -> EVP_DigestSignInit -> do_sigver_init -> ctx->pctx->pmeth->digest_custom()
> > ctx->pctx->pmeth->digest_custom() 这里为pkey_sm2_digest_custom()。
> > pkey_sm2_digest_custom()中会计算Z值的，对应预处理1过程。
> 
> 研究了下openssl源码，同意你说的，内部已经计算了Z值。
> 
> 但是有一点，与我的理解不一致：
> 
> 对原文的处理： 根据《GMT 0003.2-2012 SM2椭圆曲线公钥密码算法第2部分：数字签名算法》6.1中规定：Z值和原文是拼接的关系，而不是将Z值和原文哈希后拼接。
> 
> 参考《SSL VPN规范》6.4.4.8中描述，运算内容的部分。

是的，目前的实现存在问题 ，和标准不完全一致，近期会着手修改。

**Comment by Linshiqi** [comment]
@532810439 我觉得你是对的，内部确实计算了Z值，但是使用的是Z值和原文hash，而不是Z值和源码，修改之后才是服务国密标准文件中关于预处理中的描述

**Comment by Linshiqi** [comment]
@532810439 我觉得你是对的，内部确实计算了Z值，但是使用的是Z值和原文hash，而不是Z值和源码，修改之后才是服务国密标准文件中关于预处理中的描述

**Comment by ZotrusTech** [comment]
#582 发了一个pull request，可以看看

**Comment by zzl360** [comment]
https://github.com/jntass/TASSL-1.1.1/issues/12  https://github.com/guanzhi/GmSSL/pull/1361
可以参考以上讨论，根据GM/T 0024的规范，目前tongsuo实现的并没有问题。在客户端证书验证的时候，是需要做2次sm3的计算的。
