### ISSUE TITLE
使用sm4-cbc加解密文件报错

### ISSUE THREAD

**Issue by Harry-KE** [BabaSSL/BabaSSL#133]
**环境**
系统：Windows 10，21H1，19043.1288
硬件：Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz   2.11 GHz，RAM 8.00 GB
**编译**
_perl Configure VC-WIN64A
nmake
nmake install_

在以上环境，执行以上命令没有报错，完成编译（编译器Microsoft Visual Studio Professional 2019，Version 16.11.0）。
BabaSSL版本：
_BabaSSL 8.2.1
OpenSSL 1.1.1h-dev  xx XXX xxxx_

使用BabaSSL的SM4-CBC加密文件报错，内容如下
_openssl sm4-cbc -e -in NOTE.txt -out NOTE.txt.sm4
enter sm4-cbc encryption password:
Verifying - enter sm4-cbc encryption password:
*** WARNING : deprecated key derivation used.
Using -iter or -pbkdf2 would be better.
101288:error:25078067:DSO support routines:win32_load:could not load the shared library:crypto\dso\dso_win32.c:108:filename(providers.dll)
101288:error:25070067:DSO support routines:DSO_load:could not load the shared library:crypto\dso\dso_lib.c:162:
101288:error:0E07506E:configuration file routines:module_load_dso:error loading dso:crypto\conf\conf_mod.c:224:module=providers, path=providers
101288:error:0E076071:configuration file routines:module_run:unknown module name:crypto\conf\conf_mod.c:165:module=providers_

但是使用openSSL可以正常加密，内容如下：
_openssl sm4-cbc -e -in NOTE.txt -out NOTE.txt.sm4
enter SM4-CBC encryption password:
Verifying - enter SM4-CBC encryption password:
*** WARNING : deprecated key derivation used.
Using -iter or -pbkdf2 would be better._
openSSL版本：
_OpenSSL 3.0.0 7 sep 2021 (Library: OpenSSL 3.0.0 7 sep 2021)_

**Comment by dongbeiouba** [comment]
providers.dll文件是哪来的？是不是不应该被BabaSSL load

**Comment by Harry-KE** [comment]
使用BabaSSL 8.2.1源码编译，没做任何修改，通过命令行给文件加密报了上述错误，电脑里没有providers.dll

**Comment by Harry-KE** [comment]
找到问题原因了，没有设置OPENSSL_CONF环境变量
