### ISSUE TITLE
用openssl 握手测试国密服务器发现不能携带SNI信息

### ISSUE THREAD

**Issue by aifeiasdf** [BabaSSL/BabaSSL#141]
测试命令 ： ./openssl s_client -connect test.domain.com:443 -cipher ECC-SM2-SM4-CBC-SM3 -enable_ntls -ntls  
抓包发现没有携带SNI信息，即是使用了servername 参数显示指定也没有
tlsv1.2 正常

**Comment by dongbeiouba** [comment]
> 测试命令 ： ./openssl s_client -connect test.domain.com:443 -cipher ECC-SM2-SM4-CBC-SM3 -enable_ntls -ntls 抓包发现没有携带SNI信息，即是使用了servername 参数显示指定也没有 tlsv1.2 正常

master支持的，可以使用master分支测试；
后续可以升级到8.3.0版本。

**Comment by aifeiasdf** [comment]
<img width="1016" alt="430DAB36-D999-4B1D-BBE4-A1FC9FF73337" src="https://user-images.githubusercontent.com/3370669/148524668-f7d513e7-cbde-4c20-aabc-cf99b69fd7d1.png">

openssl  version
BabaSSL: BabaSSL 8.3.0-dev (BabaSSL-Library: BabaSSL 8.2.2-dev)
OpenSSL 1.1.1h-dev  xx XXX xxxx

**Comment by aifeiasdf** [comment]
怀疑是主机问题，换一台主机重新编译后即可 close
