### ISSUE TITLE
dso_dlfcn.c compile error

### ISSUE THREAD

**Issue by zhangxiangda** [BabaSSL/BabaSSL#143]
# develop environment
ubuntu 20.04 gcc 9.3.0 contains libdl.so list bellow
/lib/i386-linux-gnu/libdl.so
/lib/x86_64-linux-gnu/libdl.so

# compile issue 
xquic with babassl compile error throw info: dso_dlfcn.c undefined reference to 'dlopen'

https://github.com/alibaba/xquic #Build with BabaSSL

![babassl](https://user-images.githubusercontent.com/97495486/148880295-c09421a4-1cff-4ebf-8f68-e619d9aacada.png)

**Comment by Kulsk** [comment]
libdl.so链接问题

**Comment by zhangxiangda** [comment]
fix that when trying to add libdl.so absolute lib path to compile
