### ISSUE TITLE
建议把《NTLS使用手册》中的套件名称更新为《GB/T 38636-2020》的名称

### ISSUE THREAD

**Issue by xuyang2** [BabaSSL/BabaSSL#144]
建议把[《NTLS使用手册》]( https://github.com/BabaSSL/BabaSSL/wiki/NTLS%E4%BD%BF%E7%94%A8%E6%89%8B%E5%86%8C)中的套件名称更新为《GB/T 38636-2020》的：

{0xe0,0x13}
`ECC-SM2-WITH-SM4-SM3` -> `ECC-SM2-SM4-CBC-SM3`

{0xe0,0x11}
`ECDHE-SM2-WITH-SM4-SM3` -> `ECDHE-SM2-SM4-CBC-SM3`

https://github.com/BabaSSL/BabaSSL/blob/683f3013b47c62cf9b68b7d63fd95b7cdf3aadaa/include/openssl/ntls.h#L23-L40

**Comment by sdhzdmzzl** [comment]
同意，其实tlcp可以看做是0024的国标版或者修订版，应该以tlcp为准。

**Comment by jinjiu** [comment]
已更新，谢谢
