### ISSUE TITLE
ECDHE-SM2-WITH-SM4-SM3与Client Auth？

### ISSUE THREAD

**Issue by johnshajiang** [BabaSSL/BabaSSL#149]
https://babassl.readthedocs.io/zh/latest/Tutorial/SM/ntls/
正在参考NTLS在上面文档中的例子，发现在使用ECDHE-SM2-WITH-SM4-SM3时，要求客户端也要提供证书，
```
openssl s_client -connect 127.0.0.1:4433 -cipher ECDHE-SM2-WITH-SM4-SM3 \
    -sign_cert test_certs/double_cert/CS.cert.pem \
    -sign_key test_certs/double_cert/CS.key.pem \
    -enc_cert test_certs/double_cert/CE.cert.pem \
    -enc_key test_certs/double_cert/CE.key.pem \
    -enable_ntls -ntls
```
在实际的握手中，也确实看到了`CertificateRequest`消息。
这是TLCP(GB/T 38636-2020)规定的吗？

**Comment by xuyang2** [comment]
@johnshajiang FYI, see https://github.com/BabaSSL/BabaSSL/issues/41

**Comment by InfoHunter** [comment]
> 这是TLCP(GB/T 38636-2020)规定的吗？

我记得好像最早是在GM/T 0024里规定的

**Comment by johnshajiang** [comment]
看了一下TLCP的国标，它确实是提到了
> ServerECDHEParams
服务端的密钥交换参数，当使用SM2算法时，交换的参数见GB/T 35276，...

而`GB/T 35276`中定义的`SM2`密钥交换算法的参数中就包括了客户端的公钥。

**Comment by johnshajiang** [comment]
顺便问一下，示例[1]中的命令都没有设置`CA`，为什么证书的验证能够成功？

```
openssl s_server -accept 127.0.0.1:4433 \
    -enc_cert test_certs/double_cert/SE.cert.pem \
    -enc_key test_certs/double_cert/SE.key.pem \
    -sign_cert test_certs/double_cert/SS.cert.pem \
    -sign_key test_certs/double_cert/SS.key.pem \
    -enable_ntls
```

```
openssl s_client -connect 127.0.0.1:4433 -cipher ECC-SM2-WITH-SM4-SM3 -enable_ntls -ntls
```

[1] https://babassl.readthedocs.io/zh/latest/Tutorial/SM/ntls/
