### ISSUE TITLE
certificate_types应该包含ecdsa_sign，而非dss_sign

### ISSUE THREAD

**Issue by johnshajiang** [BabaSSL/BabaSSL#151]
使用`ECDHE-SM2-WITH-SM4-SM3`，s_server/s_client显示的`CertificateRequest`消息如下，
```
    CertificateRequest, Length=5
      certificate_types (len=2)
        rsa_sign (1)
        dss_sign (2)
      certificate_authorities (len=0)
```
但`TLCP`定义的`certificate_types`应该只有`rsa_sign(1)`，`ecdsa_sign(64)`和`ibc_params(80)`。

**Comment by johnshajiang** [comment]
另外，`ecdsa_sign`与实际的国密证书也不是太切合吧？
根据RFC 4492 section 5.6 [1]
```
ECDSA_sign              Certificate MUST contain an
                                  ECDSA-capable public key and
                                  be signed with ECDSA.
```
但国密证书的签名算法往往是`SM3withSM2`。

而且，`TLCP`是不是应该把`ecdsa_fixed_ecdh(66)`加进去？
```
ECDSA_fixed_ECDH        Certificate MUST contain an
                                  ECDH-capable public key on the
                                  same elliptic curve as the server's
                                  long-term ECDH key.  This certificate
                                  MUST be signed with ECDSA.
```

[1] https://www.rfc-editor.org/rfc/rfc4492#section-5.6

**Comment by dongbeiouba** [comment]
> 使用`ECDHE-SM2-WITH-SM4-SM3`，s_server/s_client显示的`CertificateRequest`消息如下，
> 
> ```
>     CertificateRequest, Length=5
>       certificate_types (len=2)
>         rsa_sign (1)
>         dss_sign (2)
>       certificate_authorities (len=0)
> ```
> 
> 但`TLCP`定义的`certificate_types`应该只有`rsa_sign(1)`，`ecdsa_sign(64)`和`ibc_params(80)`。

收到，后续会修复这个问题。

应该删除dss_sign，增加ecdsa_sign。

**Comment by johnshajiang** [comment]
我只是猜测，目前在`BabaSSL`的实现中，`certificate_types`是不是并没有实际的用处？
无论显示何种`ClientCertificateType`，其实并不影响握手？
