### ISSUE TITLE
Why order TLS_SM4_CCM_SM3 before TLS_SM4_GCM_SM3 by default?

### ISSUE THREAD

**Issue by liweitianux** [BabaSSL/BabaSSL#153]
In [`include/ssl.h#L212`](https://github.com/BabaSSL/BabaSSL/blob/master/include/openssl/ssl.h#L212), the `TLS_SM4_CCM_SM3` ciphersuite is placed **before** the `TLS_SM4_GCM_SM3`:

```c
#  define SM4_CIPHERSUITES ":TLS_SM4_CCM_SM3" \
                           ":TLS_SM4_GCM_SM3"
```

So by default, BabaSSL server would prefer `TLS_SM4_CCM_SM3` over `TLS_SM4_GCM_SM3`.  However, I don't see the meaning of such a behavior.  In reality, the GCM mode has far more support than the CCM mode.  For example, browsers may only support the GCM mode.

Moreover, the [RFC8998 standard](https://datatracker.ietf.org/doc/html/rfc8998) defines `TLS_SM4_GCM_SM3` (0x00,0xC6) **before** `TLS_SM4_CCM_SM3` (0x00,0xC7).  So I think it makes more sense that BabaSSL also adopts the same order and prefer GCM over CCM.

Any ideas?

**Comment by dongbeiouba** [comment]
Many thanks. I will fix the issue later.
