### ISSUE TITLE
请问现在是否已支持windows下开启ntls编译

### ISSUE THREAD

**Issue by f1460330800** [BabaSSL/BabaSSL#163]
请问现在是否已支持windows下开启ntls编译，如果现在暂时未支持，计划什么时候可以开启ntls进行windows下编译

**Comment by dongbeiouba** [comment]
> 请问现在是否已支持windows下开启ntls编译，如果现在暂时未支持，计划什么时候可以开启ntls进行windows下编译

master分支和8.2-stable分支已经支持Windows上开启NTLS，欢迎使用。
