### ISSUE TITLE
TLS 1.3 + 国密单证书

### ISSUE THREAD

**Issue by 532810439** [BabaSSL/BabaSSL#164]
经测试，TLS 1.3 + 国密单证书，需要设置SSL_CTX_enable_sm_tls13_strict(ctx);
国密双证书，需要设置SSL_CTX_enable_ntls(ctx);

如果按照这个顺序
SSL_CTX_enable_ntls(ctx);
SSL_CTX_enable_sm_tls13_strict(ctx);

实际上哪个生效？是TLS 1.3 + 国密单证书生效还是双证书生效，还是都生效？

**Comment by InfoHunter** [comment]
参考：https://babassl.readthedocs.io/zh/latest/Tutorial/SM/8998/
