### ISSUE TITLE
ECCClientKeyExchange 消息体中的ECCEncryptedPreMasterSecret内容最后面多了1个0或2个0

### ISSUE THREAD

**Issue by xiezhaokun** [BabaSSL/BabaSSL#166]
ECCClientKeyExchange 消息中的ECCEncryptedPreMasterSecret内容最后面多了1个0或2个0。

**Comment by jinjiu** [comment]
有抓包的截图吗，发上来看看

**Comment by xiezhaokun** [comment]
> 有抓包的截图吗，发上来看看
![babassl-clientKeyExchange](https://user-images.githubusercontent.com/21187562/154650596-4c8e698f-4412-47ef-aea4-2cf8b298f685.PNG)

**Comment by jinjiu** [comment]
原因是这样：
加密之前先通过函数 sm2_ciphertext_size 计算出加密所需的内存长度为 157，然后申请157字节长度的内存空间，最后再进行加密，将加密结果写入这157字节的内存中，但加密的结果真实长度少了1个或者2个字节，这是正常的

**Comment by xiezhaokun** [comment]
> 原因是这样： 加密之前先通过函数 sm2_ciphertext_size 计算出加密所需的内存长度为 157，然后申请157字节长度的内存空间，最后再进行加密，将加密结果写入这157字节的内存中，但加密的结果真实长度少了1个或者2个字节，这是正常的


使用JDK 的 DerValue处理结尾带0的数据，会抛出 `extra data given to DerValue constructor`;
```
DerValue derValue = new DerValue(data)；
```
使用BC 库的 ASN1Sequence 处理数据，会抛出 `Extra data detected in stream`;
```
ASN1Sequence asn1Sequence = ASN1Sequence.getInstance(data);
```
这样对于其他三方件的兼容性不是很好。

**Comment by dongbeiouba** [comment]
> > 原因是这样： 加密之前先通过函数 sm2_ciphertext_size 计算出加密所需的内存长度为 157，然后申请157字节长度的内存空间，最后再进行加密，将加密结果写入这157字节的内存中，但加密的结果真实长度少了1个或者2个字节，这是正常的
> 
> 使用JDK 的 DerValue处理结尾带0的数据，会抛出 `extra data given to DerValue constructor`;
> 
> ```
> DerValue derValue = new DerValue(data)；
> ```
> 
> 使用BC 库的 ASN1Sequence 处理数据，会抛出 `Extra data detected in stream`;
> 
> ```
> ASN1Sequence asn1Sequence = ASN1Sequence.getInstance(data);
> ```
> 
> 这样对于其他三方件的兼容性不是很好。

收到，非常感谢。

结尾确实不应该包含多余的0，将于近期修复。
