### ISSUE TITLE
TLS + SM2单证书 使用疑问请教

### ISSUE THREAD

**Issue by Sovea** [BabaSSL/BabaSSL#170]
### 【主题需求】
请教关于改造项目支持TLS + SM2单证书

### 【问题描述】
目前在改造[spice](https://gitlab.freedesktop.org/spice)项目，希望使其支持使用基于SM2的TLS进行加密。
(当前已将spice-protocol、spice、spice-gtk在以babassl替换opensl的环境下进行编译，RSA证书使用成功)

spice项目支持使用TLS，需要使用**ca --> server两层结构的x509 certificate 证书**(主要使用ca-cert.pem、server-cert.pem、server-key.pem)，目前尝试过使用文档中《使用BabaSSL签发SM2证书》签发证书，未成功。**不清楚是证书使用有误还是使用场景不符合这样签发的规定**。

### 【问题核心】
希望以BaBaSSL替代OpenSSL，以此作为环境对项目([spice](https://gitlab.freedesktop.org/spice))进行编译，使原项目能使用基于sm2单证书的TLS进行加密传输。
目前希望得到 **(满足ca --> server两层结构的x509 certificate 证书)** 这样情况的正确签发方式、命令或文件。

### 【其他】
希望各位能为我答疑，如有需要补充的前提、介绍、文件我会及时补充。

**Comment by dongbeiouba** [comment]
是签发SM2单证书失败吗？

发一下完整的命令和错误信息。

**Comment by Sovea** [comment]
> 是签发SM2单证书失败吗？
> 
> 发一下完整的命令和错误信息。

感谢回复，我刚刚对比RSA的证书签发过程重新调整了一下命令，目前好像验证通过了，还是请您帮忙看一下有没有什么问题。

```shell
openssl ecparam -genkey -name SM2 -out ca-key.pem
openssl req -new -key ca-key.pem -out ca-key.csr -sm3 -sigopt "sm2_id:1234567812345678" -utf8 -subj "/C=IL/L=Raanana/O=Red Hat/CN=my CA"
openssl x509 -req -in ca-key.csr  -signkey ca-key.pem -out ca-cert.pem -sm3 -sm2-id 1234567812345678 -sigopt "sm2_id:1234567812345678"


openssl ecparam -genkey -name SM2 -out server-key.pem
openssl req -new -key server-key.pem -out server-key.csr -sm3 -sigopt "sm2_id:1234567812345678" -utf8 -subj "/C=IL/L=Raanana/O=Red Hat/CN=my server"
openssl x509 -req -days 1095 -in server-key.csr -CA ca-cert.pem -CAkey ca-key.pem -set_serial 01 -out server-cert.pem -sm3 -sm2-id 1234567812345678 -sigopt "sm2_id:1234567812345678"
```

**Comment by Sovea** [comment]
> 是签发SM2单证书失败吗？
> 
> 发一下完整的命令和错误信息。

如果我如上所示的证书签发没有明显问题，本次改造应该基本成功，再次**感谢BaBaSSL项目**。

我还想趁此机会询问一些问题求证一下该改造路线的正确可行性：

- BaBaSSL 中TLS 支持的SM2单证书 **确实支持** 在不更改或少改动源代码情况下完成openssl旧项目的TLS支持的国密化拓展？
- 客户端是否不一定需要开启 SSL_CTX_set_ciphersuites(ctx, "TLS_SM4_GCM_SM3")，如果是，什么情况下应该开启？
- 如果只使用支持了SM的TLS，是否不应开启enable-ntls，开启后是否会有影响？

**Comment by dongbeiouba** [comment]
> > 是签发SM2单证书失败吗？
> > 发一下完整的命令和错误信息。
> 
> 如果我如上所示的证书签发没有明显问题，本次改造应该基本成功，再次**感谢BaBaSSL项目**。
> 
> 我还想趁此机会询问一些问题求证一下该改造路线的正确可行性：
> 
> * BaBaSSL 中TLS 支持的SM2单证书 **确实支持** 在不更改或少改动源代码情况下完成openssl旧项目的TLS支持的国密化拓展？
> * 客户端是否不一定需要开启 SSL_CTX_set_ciphersuites(ctx, "TLS_SM4_GCM_SM3")，如果是，什么情况下应该开启？
> * 如果只使用支持了SM的TLS，是否不应开启enable-ntls，开启后是否会有影响？

RFC 8998标准在TLS 1.3协议中增加了国密算法套件，BabaSSL在已有的TLS 1.3协议上支持国密相关算法，上层应用直接使用这些国密算法的套件就好了，改动很少就可以使用。

如果客户端或服务端未明确设置TLS 1.3加密套件，TLS_SM4_GCM_SM3是排在TLS 1.3默认密码套件的后面（参考TLS_DEFAULT_CIPHERSUITES），意味着协商密码套件的时候会使用其他套件，例如TLS_AES_256_GCM_SHA384。如果只想使用TLS_SM4_GCM_SM3这个密码套件来建立TLS 1.3，那就需要调用SSL_CTX_set_ciphersuites(ctx, "TLS_SM4_GCM_SM3")。

如果只想使用TLS 1.3 + SM单证书，就不用开启enable-ntls，服务端可以同时支持TLS和NTLS的，可以参考一下s_server.c代码，或者开源tengine代码。
