### ISSUE TITLE
tengine2.3.3集成BabaSSL时如何只配置SM2证书？

### ISSUE THREAD

**Issue by qwe857359351a** [BabaSSL/BabaSSL#191]
目前SM2单向和双向都已联调通过了，但是还想把RSA算法的支持给预留出来，nginx配置文件暂时不体现RSA的配置，支持的协议现在配置为TLSv1.1 TLSv1.2 TLSv1.3，现在发现个问题，当把RSA的配置注释掉之后，只保留SM2证书，通过国密浏览器访问就是失败页面显示：
`使用了不受支持的协议。
ERR_SSL_VERSION_OR_CIPHER_MISMATCH`
通过抓包，握手时也确实发送了国密的算法套件。
当把RSA的配置放开，就能成功访问，并且算法套件也是用的国密算法。
现在不管怎么调整配置，都是这样一个情况，RSA证书可以不用，但是必须要配，实在没辙了，请问这个问题该如何解决？

**Comment by dongbeiouba** [comment]
> 目前SM2单向和双向都已联调通过了，但是还想把RSA算法的支持给预留出来，nginx配置文件暂时不体现RSA的配置，支持的协议现在配置为TLSv1.1 TLSv1.2 TLSv1.3，现在发现个问题，当把RSA的配置注释掉之后，只保留SM2证书，通过国密浏览器访问就是失败页面显示： `使用了不受支持的协议。 ERR_SSL_VERSION_OR_CIPHER_MISMATCH` 通过抓包，握手时也确实发送了国密的算法套件。 当把RSA的配置放开，就能成功访问，并且算法套件也是用的国密算法。 现在不管怎么调整配置，都是这样一个情况，RSA证书可以不用，但是必须要配，实在没辙了，请问这个问题该如何解决？

发一下tengine配置，还有抓包的截图，我本地尝试复现一下。

**Comment by qwe857359351a** [comment]
> > 目前SM2单向和双向都已联调通过了，但是还想把RSA算法的支持给预留出来，nginx配置文件暂时不体现RSA的配置，支持的协议现在配置为TLSv1.1 TLSv1.2 TLSv1.3，现在发现个问题，当把RSA的配置注释掉之后，只保留SM2证书，通过国密浏览器访问就是失败页面显示： `使用了不受支持的协议。 ERR_SSL_VERSION_OR_CIPHER_MISMATCH` 通过抓包，握手时也确实发送了国密的算法套件。 当把RSA的配置放开，就能成功访问，并且算法套件也是用的国密算法。 现在不管怎么调整配置，都是这样一个情况，RSA证书可以不用，但是必须要配，实在没辙了，请问这个问题该如何解决？
> 
> 发一下tengine配置，还有抓包的截图，我本地尝试复现一下。

浏览器使用的是国产红莲浏览器，也可以使用密信国密浏览器
`server {
        listen       443 ssl;
        ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;

        # RSA证书，需要配置在SM2证书之前
        #ssl_certificate      cert.pem;
        #ssl_certificate_key  cert.key;

        # SM2证书，签名证书在前，加密证书在后，证书与密钥必须匹配
        ssl_certificate      server_sign.pem;
        ssl_certificate_key  server_sign.key;
        ssl_certificate      server_enc.pem;
        ssl_certificate_key  server_enc.key;

        location / {
            root   html;
            index  index.html index.htm;
        }
    }`
![image](https://user-images.githubusercontent.com/14050132/156094395-ba51b5d6-c613-4fbe-927e-cf63bf5eb5b3.png)
![image](https://user-images.githubusercontent.com/14050132/156094886-7ef70a35-9313-482b-9c6f-60c8945d2cf3.png)
![image](https://user-images.githubusercontent.com/14050132/156095061-5be1d3c7-7bb2-420e-bb7c-6a8c908793f3.png)

**Comment by dongbeiouba** [comment]
tengine配置中没有看到
```
enable_ntls  on;
```
加上试试？

**Comment by qwe857359351a** [comment]
> tengine配置中没有看到
> 
> ```
> enable_ntls  on;
> ```
> 
> 加上试试？

提示：nginx: [emerg] unknown directive "enable_ntls"
我们使用的是tengine官网发布的2.3.3版本
编译安装命令为：
`./configure \
--prefix="/home/tengine" \
--add-module=./modules/ngx_http_upstream_check_module \
--with-debug \
--with-openssl=../BabaSSL-master \
--with-openssl-opt=enable-ntls \
--with-zlib=../zlib-1.2.11 \
--with-pcre-jit --with-pcre=../pcre-8.44 \
--with-jemalloc=../jemalloc-master \
--with-http_ssl_module \
--with-http_v2_module`

**Comment by qwe857359351a** [comment]
> > 2.3.3版本
> 
> tengine 2.3.3版本还不支持国密TLS通信，目前需要使用tengine master分支代码。

我们现在确实是使用这种方式调通了，当使用chrome时会自动使用RSA国际算法，当使用国密浏览器时就是GM算法，但是尴尬的是RSA的不管用不用，都必须配置才行

**Comment by dongbeiouba** [comment]
建议参考https://github.com/alibaba/tengine/blob/master/modules/ngx_openssl_ntls/README.md

**Comment by qwe857359351a** [comment]
> 建议参考https://github.com/alibaba/tengine/blob/master/modules/ngx_openssl_ntls/README.md

好吧，感谢

**Comment by qwe857359351a** [comment]
> > > 目前SM2单向和双向都已联调通过了，但是还想把RSA算法的支持给预留出来，nginx配置文件暂时不体现RSA的配置，支持的协议现在配置为TLSv1.1 TLSv1.2 TLSv1.3，现在发现个问题，当把RSA的配置注释掉之后，只保留SM2证书，通过国密浏览器访问就是失败页面显示： `使用了不受支持的协议。 ERR_SSL_VERSION_OR_CIPHER_MISMATCH` 通过抓包，握手时也确实发送了国密的算法套件。 当把RSA的配置放开，就能成功访问，并且算法套件也是用的国密算法。 现在不管怎么调整配置，都是这样一个情况，RSA证书可以不用，但是必须要配，实在没辙了，请问这个问题该如何解决？
> > 
> > 
> > 发一下tengine配置，还有抓包的截图，我本地尝试复现一下。
> 
> 浏览器使用的是国产红莲浏览器，也可以使用密信国密浏览器 `server { listen 443 ssl; ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;
>
