### ISSUE TITLE
server sends more than two certificates?

### ISSUE THREAD

**Issue by johnshajiang** [BabaSSL/BabaSSL#203]
针对TLCP标准
如果server除了传递认证证书与加密证书，还需要传递这些证书所在的证书链的上游CA，如int_ca1，int_ca2，应该如何处理呢？

使用BabaSSL 8.3.0-dev，可以看到s_server会使用如下顺序进行传递，
`sign_cert - enc_cert - int_ca1 - int_ca2`

若使用TASSL 1.1.1k，它的s_server会使用如下顺序进行传递，
`sign_cert - int_ca1 - int_ca2 - enc_cert `

这样是不是就造成交互上的兼容性问题了？
使用BabaSSL s_server + TASSL s_client测试时，TASSL似乎不能正确地识别出加密证书。

**Comment by zzl360** [comment]
证书链这块，《GM/T 0024-2014 SSL VPN 技术规范》和《GB/T 38636-2020 信息安全技术传输层密码协议（TLCP）》都没有明确规范。目前现实使用中，一般是签名证书+加密证书+证书链这个顺序。可以参考https://sm2only.ovssl.cn等国密网站站点。

**Comment by johnshajiang** [comment]
这是不是也说明签名证书与加密证书只能是由同一个(中间)CA发布？

**Comment by zzl360** [comment]
是的，实际情况也是这样的，用户使用csr文件向CA机构申请国密证书的，CA会发放1个签名证书和1对（加密证书+私钥）。如果不用签名证书所属CA发放的加密证书，而是使用另一个合法的加密证书+私钥，可以把两个证书的CA证书都放到加密证书后边，有些客户端可以处理这种情况。

**Comment by zzl360** [comment]
#117

**Comment by johnshajiang** [comment]
> #117

谢谢这条信息。
