### ISSUE TITLE
NTLS是否支持session resumption？

### ISSUE THREAD

**Issue by johnshajiang** [BabaSSL/BabaSSL#227]
TLCP协议提到了基于session ID的session resumption，想了解NTLS是否支持这个特性？
若支持，如何使用s_server和s_client进行测试？

**Comment by InfoHunter** [comment]
s_server按照NTLS正常启动，s_client连接的时候用 -sess_out / -sess_in 参数来保存/恢复session。比如第一次用s_client -sess_out将session写入一个文件，第二次再使用s_client -sess_in从该文件恢复NTLS session。

NTLS的话，session ticket是支持的，至于session ID，需要问下 @dongbeiouba

**Comment by dongbeiouba** [comment]
> TLCP协议提到了基于session ID的session resumption，想了解NTLS是否支持这个特性？ 若支持，如何使用s_server和s_client进行测试？

NTLS支持session resumption，session ID和session ticket两种复用机制都是支持的。

基于session ID机制，使用s_server和s_client测试示例如下：
```
# 服务端
/opt/babassl/bin/openssl s_server -accept 127.0.0.1:8443-cert_chain /path/to/sm2_chain.crt -build_chain -enc_cert /path/to/sm2_enc.crt -enc_key /path/to/sm2_enc.key -sign_cert /path/to/sm2_sign.crt -sign_key /path/to/sm2_sign.key -enable_ntls  -www -quiet

# 客户端
/opt/babassl/bin/openssl s_client -connect 127.0.0.1:8443 -cipher ECC-SM2-SM4-CBC-SM3 -sess_out sess1.pem -no_ticket -ign_eof -CAfile /path/to/ca_sm2.crt -enable_ntls -ntls


/opt/babassl/bin/openssl s_client -connect 127.0.0.1:8443 -cipher ECC-SM2-SM4-CBC-SM3 -sess_in sess1.pem -no_ticket -ign_eof -CAfile /path/to/ca_sm2.crt -enable_ntls -ntls
```

**Comment by johnshajiang** [comment]
看起来测试方式和OpenSSL是一样的。
