### ISSUE TITLE
嵌入式编译裁剪

### ISSUE THREAD

**Issue by 532810439** [BabaSSL/BabaSSL#231]
现在我需要在嵌入式设备上使用。需求如下：
1、使用RSA、AES、SM2/SM3/SM4等比较常见的算法，滤掉过时的，不常使用的算法。
2、使用tls1.2、tls1.3、国密ssl，过滤不常用算法的协商套件。

我现在的编译脚本是：
./Configure --prefix=xxx --cross-compile-prefix=xxx linux-armv4 no-asm no-afalgeng no-asan no-async no-bf no-blake2 no-camellia no-capieng no-chacha no-cmac no-dtls no-ec_nistp_64_gcc_128 no-egd no-external-tests no-hw no-idea no-md2 no-mdc2 no-poly1305 no-psk no-rc2 no-rc4 no-rc5 no-rmd160 no-scrypt no-sctp no-seed no-sse2 no-tests no-unit-test no-weak-ssl-ciphers no-zlib no-zlib-dynamic shared enable-ntls -fPIC

ssl协商套件是：
TLS_AES_256_GCM_SHA384:
TLS_AES_128_GCM_SHA256:
TLS_SM4_CCM_SM3:
TLS_SM4_GCM_SM3:
ECDHE-ECDSA-AES128-GCM-SHA256:
ECDHE-RSA-AES128-GCM-SHA256:
ECDHE-ECDSA-AES256-GCM-SHA384:
ECDHE-RSA-AES256-GCM-SHA384:
DHE-RSA-AES128-GCM-SHA256:
DHE-RSA-AES256-GCM-SHA384:
ECC-SM2-SM4-CBC-SM3:
ECDHE-SM2-SM4-CBC-SM3:
ECC-SM2-SM4-GCM-SM3:
ECDHE-SM2-SM4-GCM-SM3

请问编译脚本，怎么裁剪，才可以使编译出来的so最小化？
协商套件是不是满足需求的最小化了？

**Comment by jinjiu** [comment]
可以加上这几个编译参数 no-ssl3 no-tls1 no-tls1_1

**Comment by 532810439** [comment]
> 可以加上这几个编译参数 no-ssl3 no-tls1 no-tls1_1

多谢
