### ISSUE TITLE
SSL handshake failed

### ISSUE THREAD

**Issue by 532810439** [BabaSSL/BabaSSL#234]
2022/04/26 18:27:03 [info] 109089#0: *3 client 192.168.90.14:51830 connected to 0.0.0.0:8443
2022/04/26 18:27:03 [info] 109089#0: *3 client sent no required SSL certificate while SSL handshaking, client: 192.168.90.14, server: 0.0.0.0:8443
2022/04/26 18:27:03 [crit] 109089#0: *3 SSL_shutdown() failed (SSL: error:14094123:SSL routines:ssl3_read_bytes:application data after close notify) while SSL handshaking, client: 192.168.90.14, server: 0.0.0.0:8443

**Comment by 532810439** [comment]
请问，客户端哪里错了？

**Comment by dongbeiouba** [comment]
> 请问，客户端哪里错了？

client sent no required SSL certificate while SSL handshaking

服务端开启了客户端认证，但是握手的时候客户端并没有发送证书。
