### ISSUE TITLE
国密ssl中证书导入的问题

### ISSUE THREAD

**Issue by 532810439** [BabaSSL/BabaSSL#237]
现在我已成功配置，完成国密ssl的验证。 据此链接：https://github.com/BabaSSL/BabaSSL/wiki/NTLS%E4%BD%BF%E7%94%A8%E6%89%8B%E5%86%8C

问题是：能否通过SSL_CTX_set_cert_cb这种方式，将证书和私钥导入？？

**Comment by vstinner** [comment]
Please stop notifying me on your project. I don't know BabaSSL and I don't speak Chinese.

**Comment by dongbeiouba** [comment]
> 现在我已成功配置，完成国密ssl的验证。 据此链接：https://github.com/BabaSSL/BabaSSL/wiki/NTLS%E4%BD%BF%E7%94%A8%E6%89%8B%E5%86%8C
> 
> 问题是：能否通过SSL_CTX_set_cert_cb这种方式，将证书和私钥导入？？

可以的，通过SSL_CTX_set_cert_cb设置callback，然后在callback中设置国密证书。

**Comment by 532810439** [comment]
> Please stop notifying me on your project. I don't know BabaSSL and I don't speak Chinese.

sorry
