### ISSUE TITLE
有计划支持在 Visual Studio 2022 编译吗 

### ISSUE THREAD

**Issue by Huihh** [BabaSSL/BabaSSL#244]
因为新版 OpenSSL 支持 Linux  和 VS  编译，但是其对国密支持不大完善，GMSSL 目前支持力度还不够，所以问下作者，BabaSSL 后续有计划支持 VS 编译吗，如果有计划，那大概什么时候可以支持，谢谢

**Comment by InfoHunter** [comment]
目前用VS 2022编译BabaSSL是否存在问题？

**Comment by Huihh** [comment]
没有文档说明如何在 VS 下编译，因为要在 VS  下编译，生成 dll 库，用于测试函数功能，类似 OpenSSL 一样，可以生成 dll 库，供应用程序调用，目前没有在 BabaSSL 看到相关的编译说明文档。

**Comment by wa5i** [comment]
windows 系统可以在命令行编译生成 dll 库，参考：https://github.com/BabaSSL/BabaSSL/blob/master/.github/workflows/windows.yml
![image](https://user-images.githubusercontent.com/7484739/180175232-6955bb3b-5c9e-4aca-b396-3812029c2927.png)

**Comment by Huihh** [comment]
好的  我晚点试试  谢谢
