### ISSUE TITLE
请问 TLS 1.3（RFC8998）的 Sm2 密钥交换是以什么算法实现的

### ISSUE THREAD

**Issue by WendyWjt** [BabaSSL/BabaSSL#245]
`sm2_pmeth.c` 文件中并没有关于 derive 的指针，我搜了一下，`sm2_kep.c::SM2_compute_key` 只在 NTLS 部分显示调用了，似乎 Sm2 的 GBT 规定的密钥交换算法没有在 RFC8998 中使用。但是 TLS 1.3 需要判断使用国密算法套时，密钥交换算法是 curveSm2。 请问 TLS 1.3（RFC8998）的 Sm2 密钥交换是以什么算法实现的？是 IEEE 1363 规定的基础的 DH 算法吗？

此外，关于 RFC 8998，节 1.1 表示，

> only the SM2 ... basic key exchange scheme are involved

节 3.4 表示，

> ... and an SM2 key exchange protocol **SHALL NOT** be used in the key exchange steps defined in Section 3.3

这里是否也表示，TLS 1.3 适配国密时，Sm2 GBT 中规定的密钥交换算法不应当使用，应当使用 IEEE 1363 规定的基础 DH 算法？

**Comment by zzl360** [comment]
#37 密钥协商这块用的是echde+sm2密钥对。

**Comment by WendyWjt** [comment]
好的，了解了，非常感谢
