### ISSUE TITLE
Is there a plan to sync OpenSSL?

### ISSUE THREAD

**Issue by spacewander** [BabaSSL/BabaSSL#248]
BabaSSL is [based on OpenSSL 1.1.1](https://github.com/BabaSSL/BabaSSL/blob/master/LICENSE.original). 

Since OpenSSL is under active development and fixing security vulnerabilities sometimes, Is there a plan to sync OpenSSL regularly?

**Comment by zzl360** [comment]
there is another repo https://github.com/Tongsuo-Project/Tongsuo which is based on 3.0.3
