### ISSUE TITLE
关于NTLS的测试问题

### ISSUE THREAD

**Issue by jizai** [BabaSSL/BabaSSL#27]
根据wiki页面的“NTLS使用手册”进行NTLS连接测试时，并没有-enc_cert等相关选项。在编译最新版源码后，openssl s_server -hlep中也找不到NTLS相关的选项设置，请问现在的最新版本是否可以测试NTLS了？

**Comment by dongbeiouba** [comment]
构建的时候需要开启NTLS，enable-ntls

例如：

./config enable-ntls -march=native --strict-warnings

**Comment by jizai** [comment]
感谢您的解答
