### ISSUE TITLE
在使用TLS_SM4_GCM_SM3时，KeyShareEntry中没有包含SM2公钥信息

### ISSUE THREAD

**Issue by xiaoyuwz1234** [BabaSSL/BabaSSL#37]
根据RFC8998 
3.3.1.1 clientHello中的描述“For the key_share extension, a KeyShareEntry for the "curveSM2" group MUST be included.”
在实际使用[https://github.com/BabaSSL/BabaSSL/wiki/TLS1.3---%E5%9B%BD%E5%AF%86%E5%8D%95%E8%AF%81%E4%B9%A6](url)的s_server/s_client命令行进行验证时，仅包含了x25519曲线的信息。
这是因为SM2曲线参数实际上在RFC8998中是无法使用的，所以才这样实现么？

**Comment by xiaoyuwz1234** [comment]
根据RFC8446，密钥交换算法仅能使用(EC)DH，RFC8998中KeyShareEntry 包含了一个SM2公钥信息，根据GB/T 32918.3-2016中描述的SM2密钥交换算法，计算出共享密钥需要两组对端的公钥信息。
1、如果考虑使用SM2密钥交换算法，此时通过KeyShareEntry 获取对端的一个SM2公钥信息是不能计算出共享密钥的。
2、如果考虑使用SM2密钥交换算法，通过KeyShareEntry 获取对端的一个SM2公钥信息，以及证书中的另外一个SM2公钥信息，可以计算出共享密钥，但会限制该方案只能用于双向TLS握手，即需要客户端发送certificate消息。
3、如果考虑使用SM2密钥交换算法，是否可以通过在添加一个扩展用于指定第二个SM2公钥信息。
3、如果不考虑使用SM2密钥交换算法，KeyShareEntry是否还有其他作用，或者就不加入the "curveSM2" group。

**Comment by InfoHunter** [comment]
RFC8998里不考虑使用SM2密钥交换算法，因为此方法会对TLS1.3的流程进行大幅度修改。
为了在ECDHE中使用SM2算法来生成临时密钥对，因此需要在key_share中指明对SM2的支持

**Comment by xiaoyuwz1234** [comment]
好的，明白了。
是在使用SM2证书时，并且KeyShareEntry中包含curveSM2的公钥信息时，优先考虑使用 [SM2密钥+ECDHE] 来计算共享密钥么？

**Comment by InfoHunter** [comment]
对，是指示协商的双方支持用SM2，但是最终选择还是根据服务器端的配置来选

**Comment by xiaoyuwz1234** [comment]
好的，非常感谢。多谢详细的解答。
