### ISSUE TITLE
apps/s_client.c#L885

### ISSUE THREAD

**Issue by EasyCoderWei** [BabaSSL/BabaSSL#38]
https://github.com/BabaSSL/BabaSSL/blob/45bde95ccb9c4f35ab7c4777e5f265b7e9811807/apps/s_client.c#L885
最后一个写错了（o == OPT_DTLS），应该是 o == OPT_NTLS

**Comment by dongbeiouba** [comment]
好的，我来修复一下，非常感谢！

**Comment by dongbeiouba** [comment]
Fixed by #39
