### ISSUE TITLE
SSL_SESSION_ASN1结构体新增的变量peer_extra是用来存放什么信息，看代码没有使用这个变量

### ISSUE THREAD

**Issue by EasyCoderWei** [BabaSSL/BabaSSL#43]
https://github.com/BabaSSL/BabaSSL/blob/4d03cdfa5f290b0042bd6e77f8ff333331b65425/ssl/ssl_asn1.c#L48

**Comment by InfoHunter** [comment]
应该是历史遗留代码，没用了

**Comment by EasyCoderWei** [comment]
> 应该是历史遗留代码，没用了

ok
