### ISSUE TITLE
代码中几处问题

### ISSUE THREAD

**Issue by EasyCoderWei** [BabaSSL/BabaSSL#49]
1. https://github.com/BabaSSL/BabaSSL/blob/1ac490549dff8261a17c8278fa8a6afd6834d4f4/ssl/t1_lib.c #L2368
    此处应该是处理TLS1.3逻辑（入口处已有条件限制 (TLS1_get_version(s) >= TLS1_2_VERSION && strict_mode)），使用 OPENSSL_NO_NTLS 这个宏开关是否合适？相应的赋值是否也有问题（SSL_PKEY_SM2）？

2. https://github.com/BabaSSL/BabaSSL/blob/1ac490549dff8261a17c8278fa8a6afd6834d4f4/ssl/ssl_ciph.c #L454
    最外层条件是如果定义了宏 OPENSSL_NO_SM2，内层宏条件与上 (!defined OPENSSL_NO_SM2) ，导致这个条件分支无效。

3. https://github.com/BabaSSL/BabaSSL/blob/1ac490549dff8261a17c8278fa8a6afd6834d4f4/ssl/s3_lib.c #L4391
    选择套件时，tls1_set_cert_validity 和 ssl_set_masks 两个函数已做了相应的判断，此处应该不需要再特殊处理。

4. 关于公共部分的判断NTLS_VERSION 条件应该增加附加开关条件判断，这样会更严谨。
    if (version == NTLS_VERSION)   =>  if ( s->enable_ntls == 1 && version == NTLS_VERSION )
    开启编译选项 OPENSSL_NO_NTLS 且 使能enable_ntls开关，才会走国密状态机。开关没有开启，走的是标准状态机。
    相关位置如下：
    https://github.com/BabaSSL/BabaSSL/blob/1ac490549dff8261a17c8278fa8a6afd6834d4f4/ssl/record/ssl3_record.c #L325
    https://github.com/BabaSSL/BabaSSL/blob/1ac490549dff8261a17c8278fa8a6afd6834d4f4/ssl/ssl_asn1.c #L301
    https://github.com/BabaSSL/BabaSSL/blob/1ac490549dff8261a17c8278fa8a6afd6834d4f4/ssl/ssl_cert.c #L976
    诸如此类

**Comment by dongbeiouba** [comment]
非常感谢，欢迎提交Issue和PR，这几个问题我去确认一下。
