### ISSUE TITLE
What is the difference between babaSSL and TASSL

### ISSUE THREAD

**Issue by totemofwolf** [BabaSSL/BabaSSL#5]
```
请教一下这款 SSL 和 天安的 SSL 区别是啥？

https://github.com/jntass/TASSL-1.1.1b

支持SM2 SM3 SM4国密算法和国密openssl协议的TASSL 基于openssl-1.1.1b版本
```

**Comment by totemofwolf** [comment]
``` bash
TASSL 输出

bash-4.4# bin/openssl version
OpenSSL 1.1.1b Tassl 1.4  23 Aug 2020

bash-4.4# bin/openssl
OpenSSL> ciphers
TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:DHE-RSA-AES256-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES256-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES128-SHA:RSA-PSK-AES256-GCM-SHA384:DHE-PSK-AES256-GCM-SHA384:RSA-PSK-CHACHA20-POLY1305:DHE-PSK-CHACHA20-POLY1305:ECDHE-PSK-CHACHA20-POLY1305:AES256-GCM-SHA384:PSK-AES256-GCM-SHA384:PSK-CHACHA20-POLY1305:RSA-PSK-AES128-GCM-SHA256:DHE-PSK-AES128-GCM-SHA256:AES128-GCM-SHA256:PSK-AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:ECDHE-PSK-AES256-CBC-SHA384:ECDHE-PSK-AES256-CBC-SHA:SRP-RSA-AES-256-CBC-SHA:SRP-AES-256-CBC-SHA:RSA-PSK-AES256-CBC-SHA384:DHE-PSK-AES256-CBC-SHA384:RSA-PSK-AES256-CBC-SHA:DHE-PSK-AES256-CBC-SHA:AES256-SHA:PSK-AES256-CBC-SHA384:PSK-AES256-CBC-SHA:ECDHE-PSK-AES128-CBC-SHA256:ECDHE-PSK-AES128-CBC-SHA:SRP-RSA-AES-128-CBC-SHA:SRP-AES-128-CBC-SHA:RSA-PSK-AES128-CBC-SHA256:DHE-PSK-AES128-CBC-SHA256:RSA-PSK-AES128-CBC-SHA:DHE-PSK-AES128-CBC-SHA:ECC-SM4-SM3:ECDHE-SM4-SM3:AES128-SHA:PSK-AES128-CBC-SHA256:PSK-AES128-CBC-SHA

```

**Comment by william-zk** [comment]
我们实现的国密标准不一样，TASSL实现的标准为GM0024下的两个算法套件，即`ECC-SM2-WITH-SM4-SM3`与`ECDHE-SM2-WITH-SM4-SM3`，我们实现的是这个标准下的套件：https://tools.ietf.org/html/draft-yang-tls-tls13-sm-suites-06(即将成为rfc标准)

**Comment by totemofwolf** [comment]
> 我们实现的国密标准不一样，TASSL实现的标准为GM0024下的两个算法套件，即`ECC-SM2-WITH-SM4-SM3`与`ECDHE-SM2-WITH-SM4-SM3`，我们实现的是这个标准下的套件：https://tools.ietf.org/html/draft-yang-tls-tls13-sm-suites-06 （即将成为rfc标准）


我尝试对比了一下  TASSL & BabaSSL `ciphers` 输出，发现 BabaSSL 其实将[官方TLSv1.3 ciphersuites](https://www.openssl.org/blog/blog/2017/05/04/tlsv1.3/)的 `TLS_AES_128_CCM_8_SHA256:TLS_AES_128_CCM_SHA256:` 替换成了 `TLS_SM4_CCM_SM3:TLS_SM4_GCM_SM3:` ；（真正实现 TLS 1.3 层面上的 SM 密码套件）

而 TASSL 相当于扩展了现有（TLS 1.2及以下）的算法套件：`ECC-SM2-WITH-SM4-SM3` (ECC-SM4-SM3) 和 `ECDHE-SM2-WITH-SM4-SM3` (ECDHE-SM4-SM3)

---

不知道我的理解是不是有偏差？

**Comment by william-zk** [comment]
> 发现 BabaSSL 其实将[官方TLSv1.3 ciphersuites](https://www.openssl.org/blog/blog/2017/05/04/tlsv1.3/)的 `TLS_AES_128_CCM_8_SHA256:TLS_AES_128_CCM_SHA256:` 替换成了 `TLS_SM4_CCM_SM3:TLS_SM4_GCM_SM3:`

大致上没有问题，纠正一个小错误：我们不是替换，而是新增了两个国密算法的标准ciphersuites，更细节的部分，你可以阅读这个draft:https://tools.ietf.org/html/draft-yang-tls-tls13-sm-suites-06。TASSL与我们实现的不是同一份标准，而是GM0024标准，细节见这个文档：http://www.gmbz.org.cn/main/viewfile/20180110021416665180.html

**Comment by dongbeiouba** [comment]
已回答，关闭。
