### ISSUE TITLE
BabaSSL不支持clienthello和serverhello扩展

### ISSUE THREAD

**Issue by EasyCoderWei** [BabaSSL/BabaSSL#69]
国密标准协议是基于TLS1.1协议，应该也是需要支持扩展。比如sni、重协商等。

**Comment by EasyCoderWei** [comment]
https://github.com/BabaSSL/BabaSSL/pull/36

**Comment by EasyCoderWei** [comment]
> 国密标准协议是基于TLS1.1协议，应该也是需要支持扩展。比如sni、重协商等。

我有看到一个PR:  https://github.com/BabaSSL/BabaSSL/pull/36
里面针对clienthello扩展做了一些处理。有个疑问：为什么要忽略 EMS、ETM 这两个扩展？

另外，serverhello扩展为什么发送？已经限制发送 ec_pt_format、support_group、siganature_algorithms、EMS、ETM，剩余的扩展应该没有什么影响。如果server_hello扩展没有发送的话，会影响到 alpn 和 npn 扩展。
int tls_construct_server_hello_ntls(SSL *s, WPACKET *pkt) {
    ...
    /* tls1.3: s->hello_retry_request == SSL_HRR_PENDING */
    if (!tls_construct_extensions(s, pkt, SSL_EXT_TLS1_2_SERVER_HELLO, NULL, 0))
    {
        /* SSLfatal() already called */
        return 0;
    }
    ...
}

**Comment by jinjiu** [comment]
> 国密标准协议是基于TLS1.1协议，应该也是需要支持扩展。比如sni、重协商等。

http://www.gmbz.org.cn/main/viewfile/20180110021416665180.html
GM/T 0024-2014 技术规范中并没有定义相关扩展，但在互联网场景下应该是要支持 sni 这些扩展才行，我们再 review 一下 #36

**Comment by dongbeiouba** [comment]
PR #36 主要就是为了先支持SNI；去掉和忽略一些扩展，是因为在国密握手时没有必要携带，或者导致国密握手失败。

目前国密TLS扩展支持还不完善，例如ALPN、NPN等，后续考虑按需支持。

**Comment by EasyCoderWei** [comment]
> PR #36 主要就是为了先支持SNI；去掉和忽略一些扩展，是因为在国密握手时没有必要携带，或者导致国密握手失败。
> 
> 目前国密TLS扩展支持还不完善，例如ALPN、NPN等，后续考虑按需支持。

既然国密是基于tls1.1基础上进行扩展，个人觉得tls1.1支持的扩展最好也要支持。

**Comment by InfoHunter** [comment]
> 既然国密是基于tls1.1基础上进行扩展，个人觉得tls1.1支持的扩展最好也要支持。

严格来讲国密的相关通信协议（GM/T 0024和TLCP）都不支持扩展，这些协议只是参考了TLS 1.1和TLS 1.2的协议框架，并不是简单的基于TLS协议进行的扩展。关于TLCP支持扩展的事情，我们在密标委有个课题专门是讨论这个，需要进一步推进才有可能形成正式的国家标准。在没有正式的国家标准定义扩展项之前，目前也只能根据实际使用情况支持一些必要的扩展项

**Comment by EasyCoderWei** [comment]
> PR #36 主要就是为了先支持SNI；去掉和忽略一些扩展，是因为在国密握手时没有必要携带，或者导致国密握手失败。
> 
> 目前国密TLS扩展支持还不完善，例如ALPN、NPN等，后续考虑按需支持。

s
