### ISSUE TITLE
ntls开启双向认证ECC-SM2-WITH-SM4-SM3套件报错

### ISSUE THREAD

**Issue by keshiyong** [BabaSSL/BabaSSL#71]
ntls_process_cert_verify_ntls:unknown cipher type:ssl/statem_ntls/statem_ntls_srvr.c:976:
修改源码使SSL_kSM2DHE和SSL_kSM2共用ntls_process_cv_sm2dhe连接通过
这两套件证书认证不知有无差别

**Comment by dongbeiouba** [comment]
目前还没有实现ECC-SM2-WITH-SM4-SM3的客户端认证，后续会支持。

**Comment by EasyCoderWei** [comment]
> 目前还没有实现ECC-SM2-WITH-SM4-SM3的客户端认证，后续会支持。

国密协议对于该套件有定义客户端发送上来两本证书的用途吗？比如是否参与密钥协商，还是仅仅只是身份校验？另外，如果是身份校验，那么对应的规则是什么？

**Comment by InfoHunter** [comment]
> 国密协议对于该套件有定义客户端发送上来两本证书的用途吗？比如是否参与密钥协商，还是仅仅只是身份校验？另外，如果是身份校验，那么对应的规则是什么？

没有，因为ECC-SM2-xxxx这种套件不涉及到SM2密钥交换算法（见：https://github.com/BabaSSL/BabaSSL/issues/41 里的说明），所以客户端原则上不需要提供加密证书参与密钥协商，只需要提供签名证书（在Certificate消息中），并在CertificateVerify消息中提供签名值即可使得服务器端完成对客户端的身份认证。

**Comment by EasyCoderWei** [comment]
> > 国密协议对于该套件有定义客户端发送上来两本证书的用途吗？比如是否参与密钥协商，还是仅仅只是身份校验？另外，如果是身份校验，那么对应的规则是什么？
> 
> 没有，因为ECC-SM2-xxxx这种套件不涉及到SM2密钥交换算法（见：#41 里的说明），所以客户端原则上不需要提供加密证书参与密钥协商，只需要提供签名证书（在Certificate消息中），并在CertificateVerify消息中提供签名值即可使得服务器端完成对客户端的身份认证。

ok，希望后续能够支持该功能点。

**Comment by hk520570** [comment]
> ntls_process_cert_verify_ntls:unknown cipher type:ssl/statem_ntls/statem_ntls_srvr.c:976: 修改源码使SSL_kSM2DHE和SSL_kSM2共用ntls_process_cv_sm2dhe连接通过 这两套件证书认证不知有无差别

修改后能正常使用么，最近也在做相关内容
